# .gqlgen.yml example
#
# Refer to https://gqlgen.com/config/
# for detailed .gqlgen.yml documentation.

schema: schema.graphql
exec:
  filename: generated.go
model:
  filename: models_gen.go
resolver:
  filename: resolver.go
  type: Resolver

models:
  Todo:    # Object
    fields:
      text:
        modelField: Description # Field
  NewTodo: # Input
    fields:
      userId:
        modelField: UserID      # Field
  User:
    model: github.com/vektah/gqlgen/example/config.User
    fields:
      name:
        modelField: FullName    # Method
