version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:18
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: "docker build"
          command: docker build -f .circleci/golang.Dockerfile -t gqlgen/golang .
      - run:
          name: "golang tests"
          command: docker run --rm gqlgen/golang .circleci/test.sh
      - run:
          name: "integration tests"
          command: ./.circleci/integration.sh
