---
schema: graphql.schema
exec:
  filename: generated.go
model:
  filename: models_gen.go
resolver:
  filename: resolvers.go
  type: Resolver
autobind:
  - github.com/99designs/gqlgen/example/issue_896
models: {}
